apiVersion: v1
kind: Service
metadata:
        name: svc-pod-1
        namespace: namespace-nginx
spec:
        type: NodePort
        selector:
                app: pod-1
        ports:
                - port: 80
                  nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
        name: svc-pod-1-cluster
        namespace: namespace-nginx
spec:
        type: ClusterIP
        selector:
                app: pod-1
        ports:
                - port: 9000
                  targetPort: 80
