apiVersion: v1
kind: Service
metadata:
        name: svc-pod-1
spec:
        type: NodePort
        selector:
                app: pod-1
        ports:
                - port: 80
                  nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
        name: svc-pod-1-cluster
spec:
        type: ClusterIP
        selector:
                app: pod-1
        ports:
                - port: 9000
                  targetPort: 80
